import Foundation

/// Build-time provenance for the pinned MarmotKit release.
/// Regenerated by whitenoise-ios/scripts/sync-bindings.sh on every refresh.
public enum MarmotKitVersion {
    public static let mdkSHA = "fcc6f67609113f9bb1547b7de0ba22c65437ccd3"
    public static let mdkTag = "marmotkit-v0.10.1"
    public static let builtAt = "2026-09-17T00:21:37Z"
    public static let uniffiVersion = "0.29.4"
    public static let features = "otlp-export,product-analytics-export"
}
