import Foundation

/// Build-time provenance for the pinned MarmotKit release.
/// Regenerated by whitenoise-ios/scripts/sync-bindings.sh on every refresh.
public enum MarmotKitVersion {
    public static let mdkSHA = "5b7f17f9a0162dcc8c10ba37a41b7f652d4ed154"
    public static let mdkTag = "marmotkit-snapshot-5b7f17f9a0162dcc8c10ba37a41b7f652d4ed154"
    public static let builtAt = "2026-09-08T15:16:33Z"
    public static let uniffiVersion = "0.29.4"
    public static let features = "otlp-export,product-analytics-export"
}
