import Foundation

/// Build-time provenance for the pinned MarmotKit release.
/// Regenerated by whitenoise-ios/scripts/sync-bindings.sh on every refresh.
public enum MarmotKitVersion {
    public static let mdkSHA = "5f8db5a546ae556f59622656866e21ac1e378be8"
    public static let mdkTag = "marmotkit-snapshot-5f8db5a546ae556f59622656866e21ac1e378be8"
    public static let builtAt = "2026-09-06T20:04:53Z"
    public static let uniffiVersion = "0.29.4"
    public static let features = "otlp-export"
}
