import SwiftUI
import MarmotKit

struct SettingsView: View {
    @Environment(AppState.self) private var appState
    @State private var showQR = false
    @State private var showProfileEdit = false

    var body: some View {
        Form {
            Section("Account") {
                if let active = appState.activeAccount {
                    HStack(spacing: 12) {
                        Button {
                            showProfileEdit = true
                        } label: {
                            HStack(spacing: 12) {
                                AvatarBubble(
                                    seed: active.accountIdHex,
                                    title: appState.displayName(forAccountIdHex: active.accountIdHex),
                                    pictureURL: appState.avatarURL(forAccountIdHex: active.accountIdHex)
                                )
                                .frame(width: 44, height: 44)
                                VStack(alignment: .leading, spacing: 2) {
                                    Text(appState.displayName(forAccountIdHex: active.accountIdHex))
                                        .font(.headline)
                                    Text(appState.shortNpub(forAccountIdHex: active.accountIdHex))
                                        .font(.caption.monospaced())
                                        .foregroundStyle(.secondary)
                                }
                                Spacer(minLength: 8)
                            }
                            .contentShape(.rect)
                        }
                        .buttonStyle(.plain)

                        Button {
                            showQR = true
                        } label: {
                            Image(systemName: "qrcode")
                                .font(.title3)
                                .foregroundStyle(.tint)
                        }
                        .buttonStyle(.borderless)
                        .accessibilityLabel("My QR code")

                        Image(systemName: "chevron.right")
                            .font(.footnote.weight(.semibold))
                            .foregroundStyle(.tertiary)
                    }
                    .padding(.vertical, 2)
                }

                NavigationLink {
                    AccountsView()
                } label: {
                    Label("Accounts", systemImage: "person.2.circle.fill")
                }

                NavigationLink {
                    IdentityView()
                } label: {
                    Label("Identity & Keys", systemImage: "key.fill")
                }
            }

            Section("Network") {
                NavigationLink {
                    RelaysView()
                } label: {
                    Label("Relays", systemImage: "antenna.radiowaves.left.and.right")
                }
            }

            Section("About") {
                LabeledContent("Version") {
                    Text(appVersion)
                        .foregroundStyle(.secondary)
                }
                LabeledContent("Built on") {
                    Text("MarmotKit \(marmotVersion)")
                        .font(.caption.monospaced())
                        .foregroundStyle(.secondary)
                }
            }

            Section {
                Toggle("Developer mode", isOn: Binding(
                    get: { appState.developerMode },
                    set: { appState.developerMode = $0 }
                ))
            } header: {
                Text("Developer")
            } footer: {
                Text("Adds debugging tools, including MLS group internals and diagnostics. The diagnostics console can log message text and account activity on this device.")
            }

            if appState.developerMode {
                Section("Diagnostics") {
                    NavigationLink {
                        DiagnosticsView()
                    } label: {
                        Label("Open Diagnostics", systemImage: "stethoscope")
                    }
                }
            }
        }
        .navigationTitle("Settings")
        .navigationDestination(isPresented: $showProfileEdit) {
            ProfileEditView()
        }
        .sheet(isPresented: $showQR) {
            if let hex = appState.activeAccount?.accountIdHex {
                ProfileQRView(accountIdHex: hex)
            }
        }
    }

    private var appVersion: String {
        let dict = Bundle.main.infoDictionary
        let version = dict?["CFBundleShortVersionString"] as? String ?? "—"
        let build = dict?["CFBundleVersion"] as? String ?? "—"
        return "\(version) (\(build))"
    }

    private var marmotVersion: String {
        // Compile-time constant regenerated by sync-bindings.sh; always
        // present (the MARMOT_VERSION text file isn't bundled into the app).
        MarmotKitVersion.darkmatterSHA
    }
}
